### ISSUE TITLE
Why not use an ORM Driver?

### ISSUE THREAD

**Issue by GTANAdam** [godiscourse/godiscourse#18]
Why not allow using this piece of software with MySQL or even sqlite?
All you had/have to do is implement an orm driver such as GORM or the like...

**Comment by jadeydi** [comment]
Postgresql is open source and powerful, and we need a database, so it's a personal choice.

We used https://github.com/go-pg/pg before, but it'll spend some time to learn how ORM works. And I think back-end engineer must know plain SQL, so it will spend less time for them.
Maybe sqlx is a better option, but I think a complete product is more important, so i'm focusing on finish the draft first.
